### ISSUE TITLE
Find Assembly-CSharp.dll in memory

### ISSUE THREAD

**Issue by igromanru** [zeroKilo/NoxDumper#1]
Thank you for the tool.  
I was trying to dump Assembly-CSharp.dll with your tool, but I have no idea how to find the right memory section.
Do you have an idea?

**Comment by zeroKilo** [comment]
IL opcodes and stuff is processed by the .net / mono engine, so you might not find it in the process memory. I dunno where IL opcodes are stored while in memory, so maybe you cant do that at all. google how you would dump a .net dll with ollydbg, there you can see you need multiple sections (peheader, .text, .rsrc,.data...). btw if you just want this out of a game, get the games apk, rename it to zip, extract it and just take the file from there...

greetz

**Comment by igromanru** [comment]
I've saw [this](http://www.iandrohacker.net/2015/11/tutorial-how-to-decrypt-encrypted-dll.html) tutorial. How to dump it with gdb. But I'm not sure how to install it on Nox and I thought it could also work with your dumper.

**Comment by zeroKilo** [comment]
well then just use this tutorial, its idea is simply to dump ALL sections of the process and then scan the result for the file. if you want to chat with me, im usually on reddit

greetz

**Comment by igromanru** [comment]
The question is, can I also do the same with NoxDumper. If yes, how?  
If no, I guess it would be a great feature. It's much easier to use your tool as installing gdb, don't even know if I can install it in Nox.

**Comment by zeroKilo** [comment]
ok, I added a button to dump all sections at once, but its VERY slow, hope it helps still, have fun

greetz

**Comment by igromanru** [comment]
Ok, thank you. I'll try it out.

**Comment by molixiaoge** [comment]
I think ,we can dump all memory in one big file,and use winhex to recovry it.

**Comment by zeroKilo** [comment]
yeah, then go ahead and code that, i have no intention to do so. also that would make it hard to get sections back out. if you need this, just dump all memory sections and combine them
