### ISSUE TITLE
windos 10. cant find any process

### ISSUE THREAD

**Issue by mlmn21** [zeroKilo/NoxDumper#3]
hi. in error log " The system cannot find the path specified". but i copied files in nox. exe directory.  thx for advance. nox player 6.0.1.0.

**Comment by zeroKilo** [comment]
nox_adb.exe exe must be in the same folder, thats the debug bridge program of nox that this tool uses, it seems its missing

**Comment by mlmn21** [comment]
thx for ur reply.  i did. now  i can see processes. i saw my games process. my game is mobile legend bang bang. this game is unity based. has assembly_csharp. dll. but this dll is decrypted  so i cant edit with netreflector. i want to dump it. i select process then get memory map. there are dex files. so file but i couldnt find any dll file. thx in advance.

**Comment by zeroKilo** [comment]
android is linux based, so I guess there are no dlls. unless you have found a bug in my code, im going to close this ticket
