### ISSUE TITLE
breaks if you have multiple nox open

### ISSUE THREAD

**Issue by seiyria** [zeroKilo/NoxDumper#5]
```
>nox_adb.exe connect 127.0.0.1:62001
already connected to 127.0.0.1:62001

>nox_adb.exe shell ps -t
error: more than one device/emulator

>nox_adb.exe shell  ps
error: more than one device/emulator
```

**Comment by zeroKilo** [comment]
yeah, thats a problem of nox player / adb, not my tool, if you look in the code, all I do is automate the nox_adb.exe

**Comment by seiyria** [comment]
You can do adb devices to get their IP and do adb -S ip though.

**Comment by zeroKilo** [comment]
well almost right. the nox adb can connect to multiple devices, most stuff wont work if more than one device is connected to it, also you can not tell nox adb to connect to an emulator if its already connected.  nox_adb devices -l will only show devices that the server IS already connected to, so this is not a way to iterate running emulators

I added 2 new things for you: a device selector, which scans for listening processes with the name "nox" in it and local endpoint "127.0.0.1:62XXX" (where XXX changes with each open emulator), so you can choose which connection to add for nox_adb, and then a button to disconnect all devices, in case you wanna swap. remember, dont connect more than one device at once, or the main functions wont work. I hope it helps, have a nice day, greetz 

https://github.com/zeroKilo/NoxDumper/commit/fd2ae82afa90ec59c4b21de9f9d1de25eb2bdf74

**Comment by seiyria** [comment]
thank you!
