### ISSUE TITLE
Dump Size File not correct

### ISSUE THREAD

**Issue by MikaCybertron** [zeroKilo/NoxDumper#6]
this what i was gonna dump
`StartAddress: 08000000`
`EndAddress: 091CF000`

`dumpSize: 091CF000 - 08000000`

and here is the execute command:
```
RunNoxShell("dd if=/proc/" + info.pid + "/mem of=/data/data/com.platinmodsdumper/dump bs=1 count=" + dumpSize + " skip=" + StartAddress);
```

and the result always get the dump file with size 1.5 MB to 1.7 MB only, but the original file size is 18 MB which it show in the DumpSize count, but the dump file only with size 1.5 MB to 1.7 MB
![image](https://user-images.githubusercontent.com/45533977/193469539-9a24f13b-f6ec-41d1-9fd4-d4c8fc43f74f.png)

do you know how to fix it bro??

**Comment by zeroKilo** [comment]
well this is basic linux, first off you should google how the adb console of nox can be accessed by hand and as you see I just send a normal linux command, if dd fails you need to google problems with that. here lets take the command and insert the values:

`RunNoxShell("dd if=/proc/" + info.pid + "/mem of=/data/data/com.platinmodsdumper/dump bs=1 count=" + dumpSize + " skip=" + StartAddress);`

becomes:

`dd if=/proc/ID_OF_PROCESS/mem of=/data/data/com.platinmodsdumper/dump bs=1 count=18673664 skip=134217728`

so you can test this by hand (just have to insert the process id / pid) and see if this is a problem of my tool or dd, if its my tool, pls let me know

greetz

**Comment by MikaCybertron** [comment]
> dd if=/proc/ID_OF_PROCESS/mem of=/data/data/com.platinmodsdumper/dump bs=1 count=18673664 skip=134217728

oh seems issue from the tool code, it's like it need a delay like 15 sec or more depends on performance pc until it is fully dumped

**Comment by MikaCybertron** [comment]
worked, and yeah it need a delay until fully dumped before execute other commands
![image](https://user-images.githubusercontent.com/45533977/193471267-c304e235-8a63-4ba9-b460-93c1eeb2f745.png)
